version: "3.8"
services:
  db:
    image: "mysql"
    container_name: db
    networks:
      - default
    ports:
      - "3306:3306"
      - "33060:33060"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_DATABASE: "user-service"

  node:
    container_name: node
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - default
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file: ./.env
    restart: unless-stopped
networks:
  default:
