version: "3.8"
services:
  db:
    image: "mysql"
    container_name: db
    networks:
      - default
    ports:
      - "3306:3306"
      - "33060:33060"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_DATABASE: "user-service"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "root", "--password", "123456"]
      timeout: 20s
      retries: 10
  node:
    container_name: node
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - default
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: on-failure
    env_file: ./.env
networks:
  default:
