version: "3.8"
services:
  db:
    image: "mysql"
    container_name: db
    networks:
      - default
    ports:
      - "3306:3306"
      - "33060:33060"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PORT: ${MYSQL_PORT}

  node:
    container_name: node
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - default
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PORT: ${MYSQL_PORT}
      USER_SERVICE_PORT: ${USER_SERVICE_PORT}

networks:
  default:
