version: "3.8"
services:
  db:
    image: "mysql"
    container_name: db
    networks:
      - nt
    ports:
      - "3306:3306"
      - "33060:33060"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: "user-service"
  web:
    container_name: web
    build: .
    ports:
      - "8080:8080"
    networks:
      - nt
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

networks:
  nt:
