export type PLATFORM = 'username' | 'mobile' | 'email' | 'wechat' | 'qq' | 'weibo'
export type USER_ROLE = 'normal' | 'admin'
export type GENDER = 'male' | 'female'
export type AUTH_COMMAND = 'sign_in_success' | 'sign_in_fail' | 'sign_out_success' | 'sign_out_fail'
export type CLIENT = 'web' | 'wechat'
export type OPERATING_SYSTEM = 'android' | 'ios' | 'windows' | 'linux' | 'osx'
