name: Build Dist
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  - MYSQL_DATABASE: ${{secrets.MYSQL_DATABASE}}
  - MYSQL_USERNAME: ${{secrets.MYSQL_USERNAME}}
  - MYSQL_PASSWORD: ${{secrets.MYSQL_PASSWORD}}
  - MYSQL_HOST: ${{secrets.MYSQL_HOST}}
  - MYSQL_PORT: ${{secrets.MYSQL_PORT}}
  - USER_SERVICE_PORT: ${{secrets.USER_SERVICE_PORT}}
jobs:
  build:
    runs-on: [ self-hosted, linux ]
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Run docker
        run: docker-compose up -d
      - name: Show Docker
        run: docker ps -a
